version: '3'

volumes:
  app-cache:
    driver: local

services:

  dalle-backend:
    container_name: dalle-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: unless-stopped
    ports:
      - 18080:18080
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - app-cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  dalle-interface:
    container_name: dalle-interface
    build:
      context: ./interface
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: unless-stopped
    ports:
      - 13000:3000
    labels:
      - com.centurylinklabs.watchtower.enable=false
    stdin_open: true
    tty: true
